### ISSUE TITLE
testing junk bins

### ISSUE THREAD

**Issue by melanieveale** [ollyau/generate-data#10]
Find another small galaxy (small in file size) to add to the testing list; it should have nonzero junk bins, and as a bonus could have Satellite env status to make a full set of env for the testing galaxies.

Try running the script with this galaxy; make sure nothing breaks, and make sure that the final text file and fits file come out with the correct number of bins. (I haven't looked through the fits file creator yet but it should also discard junk bins if it isn't already.)

**Comment by ollyau** [comment]
Ten smallest public FITS files belonging to galaxies with non-zero junk bins:
- UGC01332 (426240 bytes)
- NGC2256 (486720 bytes)
- NGC5208 (604800 bytes)
- NGC4839 (720000 bytes)
- NGC0741 (722880 bytes)
- UGC02261 (722880 bytes)
- NGC2320 (780480 bytes)
- NGC3937 (840960 bytes)
- NGC2208 (840960 bytes)
- NGC7386 (840960 bytes)

NGC 4839 appears to have satellite for the env parameter.  The `folded-moments.txt` and `folded-spectra.fits` appear to both discard the junk bins correctly as of the data generated using the script from commit 6548e8147a9e3d0cd58539839db198ee7dfb031e.

For reference, here are the galaxies with the smallest public FITS files overall as well as the smallest `s3-B-folded-main.fits` (as generated using the script from commit 6548e8147a9e3d0cd58539839db198ee7dfb031e and data from Box as of October 7, 2016):

Ten smallest public data FITS:
- UGC03021 (368640 bytes)
- UGC01332 (426240 bytes)
- NGC2256 (486720 bytes)
- NGC1226 (547200 bytes)
- NGC7052 (547200 bytes)
- NGC0910 (604800 bytes)
- NGC5208 (604800 bytes)
- UGC10918 (604800 bytes)
- NGC2892 (662400 bytes)
- NGC4839 (720000 bytes)

Ten smallest `s3-B-folded-main.fits`:
- UGC03021 (89280 bytes)
- NGC7052 (120960 bytes)
- UGC01332 (120960 bytes)
- NGC1226 (120960 bytes)
- UGC10918 (132480 bytes)
- NGC2256 (132480 bytes)
- NGC0910 (135360 bytes)
- NGC2892 (144000 bytes)
- NGC5208 (152640 bytes)
- NGC1132 (155520 bytes)
