### ISSUE TITLE
testing command line options

### ISSUE THREAD

**Issue by melanieveale** [ollyau/generate-data#12]
I found a bunch of bugs in the -skip option; we should test the other options (include and exclude lists) to see if they work.

**Comment by ollyau** [comment]
Fixed by @melanieveale as of b671bd10d180e4572f9a712879d3832c1d15e2d1.  The `-include` and `-exclude` (and `-skipcompleted`) arguments appear to work correctly as of 71932ba105e64f32bd29b0c564a080e003b9832b.
