### ISSUE TITLE
include and exclude lists

### ISSUE THREAD

**Issue by melanieveale** [ollyau/generate-data#2]
Seem to just be missing a line of code to turn them into sets before doing "intersection" and "difference".

**Comment by ollyau** [comment]
According to the Python documentation (https://docs.python.org/2/library/stdtypes.html#set) the non-operator versions of `intersection` and `difference` take any iterable as an argument, so changing the `include` and `exclude` lists to sets is not necessary.

> Note, the non-operator versions of union(), intersection(), difference(), and symmetric_difference(), issubset(), and issuperset() methods will accept any iterable as an argument. In contrast, their operator based counterparts require their arguments to be sets. This precludes error-prone constructions like set('abc') & 'cbs' in favor of the more readable set('abc').intersection('cbs').
